language: minimal

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - wget
      - cmake
      - libgavl-dev
      - libopencv-core-dev
      - libcairo2-dev

before_install:
  - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
  - tar xf futhark-nightly-linux-x86_64.tar.xz
  - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
  - git submodule update --init

install:
  - (cd frei0r && cmake . && make)
  - FUTHARK_COMPILER=futhark-c make

script:
  - make test
